FROM rust:1-slim AS builder
WORKDIR /usr/src/ws-server
COPY backend .
RUN cd ws-server && cargo install --path .

FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget bzip2 build-essential
COPY --from=builder /usr/src/ws-server/target/release/ws-server /usr/local/bin/ws-server
CMD ["ws-server"]
