services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.ws-server
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
