[package]
name = "wasm-nbody"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
nbody = { workspace = true }

[profile.release]
opt-level = "s"
